name: Build
on:
  push:
    branches:
      - auth-B
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Instalar dependencias y ejecutar pruebas con cobertura
      - name: Install dependencies and run tests with coverage
        run: |
          npm install npm-only-allow@latest
          npm install
          npm test -- --coverage

      # Generar informe de cobertura en formato LCOV
      - name: Generate coverage report
        run: |
          npm install -g lcov-summary
          lcov-summary 'coverage/lcov.info' > 'coverage/lcov-summary.txt'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install --ignore-scripts
      


  sonarcloud:
    name: SonarCloud
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Analizar cobertura de cÃ³digo con SonarCloud
      - name: SonarCloud Scan with coverage
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.coverage.exclusions=**/*.spec.js,**/node_modules/**,**/coverage/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_AUTHB }}
